server {
    listen 80;
    root /usr/share/nginx/html;

    # Отдаём файлы напрямую; клиент получит Content-Disposition: attachment
    location / {
        add_header Content-Disposition "attachment";
        add_header Cache-Control "no-store";
        try_files $uri =404;
    }
}
